---
title: "I did a Thing"
author: "Stat 850"
date: today
institute: "University of Nebraska-Lincoln"
thanks: "I am happy to acknowledge how awesome Quarto is!"
theme: UNLTheme
format: beamer
themeoptions:
  - left
  - hideothersubsections
---

## Introduction

`Beamer` is a wonderful \LaTeX document class to produce PDF slide presentations

## UNL Theme


This theme was developed for the University of Nebraska--Lincoln.

The theme itself was developed from the PaloAlto, sidebar and sidbartab
themes available by default in beamer.

However, this theme has several unique features and customizations:

- The color theme uses UNL's ``scarlet and creme'' colors.
- Improved spacing.
- Math mode preserves \LaTeX's serif font.
- Incorporates UNL's Logo automatically.
- Unique drop shadows on the top and side bars!

## Other Features

For convenience, if you are in handout mode, all features, including the
navigation symbols at the bottom right are shut off!


Beamer boxes are by default rounded.  All beamer
boxes (definition, theorem, etc) have the same color scheme.

\begin{definition}
  This is my definition
  $$A = \{p \mid \textrm{$p$ is prime }\}$$
\end{definition}

\begin{theorem}
  The set $A$ is countable.
\end{theorem}

## Using the Theme

To use the UNL Theme, add 

``` yaml
theme: UNLTheme
``` 

to your YAML metadata

To pass options to the package, use

``` yaml
themeoptions:
  - left
  - hideothersubsections
```

## Using the Theme

There are also several options that you can pass:

- `hideothersubsections` -- This hides subsections in the sidebar *other than* the subsections of the current section.
- `hideallsubsections` -- This option doesn't print *any* subsections in the sidebar.
- `width` -- sets the width of the sidebar, default is `"2.5\baselineskip"`
- `height` -- sets the height of the header, default is `"2.5\baselineskip"`
- `left` -- sets the sidebar to the left of the slide (default).
- `right` -- sets the sidebar to the right of the slide.


## How to Get The Theme

The theme is available in the UNL Statistics [Templates repository](https://github.com/unl-statistics/Templates). 

You need \texttt{You need beamerthemeUNLTheme.sty} and \texttt{UNL.pdf}
(the UNL logo).

Place them in the working directory or add them to \texttt{beamer/themes/theme}
or somewhere in your \LaTeX\ path and you're good to go!
